'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplicationDirecciónTIC

    Partial Public Class Equipo
        Public Property Id As Integer
        Public Property PersonaId As Integer
        Public Property EstadoId As Integer
        Public Property FechaCreación As Nullable(Of Date)
    
        Public Overridable Property Estado As Estado
        Public Overridable Property Persona As Persona
    
    End Class

End Namespace
