'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplicationDirecciónTIC

    Partial Public Class Estado
        Public Property Id As Integer
        Public Property Estado1 As String
    
        Public Overridable Property Equipoes As ICollection(Of Equipo) = New HashSet(Of Equipo)
    
    End Class

End Namespace
