'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace WebApplicationDirecciónTIC

    Partial Public Class WebApplicationDireccinTICEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=WebApplicationDireccinTICEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Equipoes() As DbSet(Of Equipo)
        Public Overridable Property Estados() As DbSet(Of Estado)
        Public Overridable Property Personas() As DbSet(Of Persona)
        Public Overridable Property Solicituds() As DbSet(Of Solicitud)
    
    End Class

End Namespace
