'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplicationDirecciónTIC

    Partial Public Class Persona
        Public Property Id As Integer
        Public Property Nombre As String
        Public Property Apellido As String
        Public Property FechaNacimiento As Nullable(Of Date)
        Public Property Pasaporte As String
        Public Property Direccion As String
        Public Property Sexo As String
        Public Property Foto As String
    
        Public Overridable Property Equipoes As ICollection(Of Equipo) = New HashSet(Of Equipo)
        Public Overridable Property Solicituds As ICollection(Of Solicitud) = New HashSet(Of Solicitud)
    
    End Class

End Namespace
