'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplicationDirecciónTIC

    Partial Public Class Solicitud
        Public Property Id As Integer
        Public Property NombreEstado As String
        Public Property FechaCreación As Nullable(Of Date)
    
    End Class

End Namespace
